{% set name = "t4" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mono/t4/archive/v{{ version }}.tar.gz
  sha256: 1608d5419321e430b1db2188b2dc8fb1e47f48b0057404df738bac3c50b3d273

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

test:
  commands:
    - t4 --help

about:
  home: https://github.com/mono/t4
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: T4 text templating engine
  dev_url: https://github.com/mono/t4

extra:
  recipe-maintainers:
    - danielnachun
